//
// Created by Lu, Chih-chiang on 2019-03-22.
//

/**
 * Find the Difference
 *
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 */

#include <string>
#include <stdexcept>

// 这道题给了我们两个字符串s和t，t是在s的任意一个地方加上了一个字符，让我们找出新加上的那个字符。这道题确实不是一道难题
// 我们可以使用位操作Bit Manipulation来做，利用异或的性质，相同位返回0，这样相同的字符都抵消了，剩下的就是后加的那个字符
// 0 ^ 0 = 0
// 0 ^ 1 = 1
// 1 ^ 0 = 1
// 1 ^ 1 = 0
class Solution {
 public:
  static char findTheDifference(std::string s, std::string t) {
    char res = 0;
    for (char c : s) {
      res ^= c;
    }
    for (char c : t) {
      res ^= c;
    }
    return res;
  }
};

int main(int argc, char *argv[]) {
  if (Solution::findTheDifference("abcd", "abcde") != 'e') {
    throw std::runtime_error("error");
  }
  return 0;
}
